# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Thresholding function for penalized regression with power penalty
#'
#' @name powThresh
#'
#' @description Gives the value of \eqn{\beta} that minimizes: \cr
#' \deqn{(\beta - z)^2/2 + \lambda|\beta|^q} \cr
#' for fixed \eqn{z}, \eqn{\lambda > 0} and \eqn{q > 0}. \cr \cr
#' For \eqn{q \le 1}, uses thresholding function given in Marjanovic and Solo (2014).
#' For \eqn{q > 1}, computed bisection.
#'
#' @usage \code{powThresh(z =  1, lambda = 1, q = 1)}
#'
#' @param \code{z} vector of values to find the minimizing beta for (\code{powThresh} is applied coordinatewise when \code{length(z)} > 1)
#' @param \code{lambda} scalar multiplier applied to penalty
#' @param \code{q} scalar power of penalty function
#'
#' @source For \eqn{q\le 1}, uses thresholding function given in Marjanovic and Solo (2014).
#' Marjanovic, Goran, and Victor Solo. "\eqn{l_q} Sparsity Penalized Linear Regression With Cyclic Descent." IEEE Transactions on Signal Processing 62.6 (2014): 1464-1475.
#'
powThresh <- function(z, lambda, q) {
    .Call('_powopt_powThresh', PACKAGE = 'powopt', z, lambda, q)
}

