# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Thresholding function for penalized regression with power penalty
#'
#' @name powThresh
#'
#' @description Gives the value of \eqn{\beta} that minimizes: \cr
#' \deqn{(\beta - z)^2/2 + \lambda|\beta|^q} \cr
#' for fixed \eqn{z}, \eqn{\lambda > 0} and \eqn{q > 0}. \cr \cr
#' For \eqn{q \le 1}, uses thresholding function given in Marjanovic and Solo (2014).
#' For \eqn{q > 1}, computed bisection.
#'
#' @usage \code{powThresh(z =  1, lambda = 1, q = 1)}
#'
#' @param \code{z} vector of values to find the minimizing beta for (\code{powThresh} is applied coordinatewise when \code{length(z)} > 1)
#' @param \code{lambda} scalar multiplier applied to penalty
#' @param \code{q} scalar power of penalty function
#'
#' @source For \eqn{q\le 1}, uses thresholding function given in Marjanovic and Solo (2014).
#' Marjanovic, Goran, and Victor Solo. "\eqn{l_q} Sparsity Penalized Linear Regression With Cyclic Descent." IEEE Transactions on Signal Processing 62.6 (2014): 1464-1475.
#'
powThresh <- function(z, lambda, q) {
    .Call(`_powopt_powThresh`, z, lambda, q)
}

#' Penalized likelihood objective function
#' @name powObj
#'
#' @description Letting \eqn{Q =X'X} and \eqn{l = X'y}, gives the value: \cr
#' \deqn{-((\beta'Q\beta - 2\beta'l)/(2\sigma^2) + \lambda \sum_{j = 1}^p |\beta_j|^q)} \cr
#' for fixed \eqn{z}, \eqn{\lambda > 0} and \eqn{q > 0}.
#'
#' @usage \code{powObj(beta, Q, l, sigmasq = 1, lambda = 1, q = 1)}
#'
#' @param \code{beta} length p vector of coefficient values to compute objective function for
#' @param \code{Q} p\eqn{\times}p matrix corresponding to \eqn{X'X}
#' @param \code{l} length p vector corresponding to \eqn{X'y}
#' @param \code{sigmasq} scalar noise variance
#' @param \code{lambda} scalar multiplier applied to penalty
#' @param \code{q} scalar power of penalty function
#'
powObj <- function(beta, Q, l, yty, sigmasq, lambda, q) {
    .Call(`_powopt_powObj`, beta, Q, l, yty, sigmasq, lambda, q)
}

